num1 = float(input('First number: '))
num2 = float(input('Second number: '))
print('Sum:', num1 + num2)
print('Subtraction:', num1- num2)
print('Multiplication:', num1 * num2)
print('Division:', num1 / num2)
